### ISSUE TITLE
Update linuxTarget.py to support encryption

### ISSUE THREAD

**Issue by lawndoc** [doctormay6/mediator#2]
linuxTarget.py is still in pre-encryption implementation. The script needs to be updated to support end-to-end encryption like windowsTarget.py

**Comment by doctormay6** [comment]
Implemented in  #b177799640410717c02ce0d2bbe9c207dc439bd8

**Comment by lawndoc** [comment]
Implemented in b177799640410717c02ce0d2bbe9c207dc439bd8
